### PR TITLE
Remove dependency on 'crypto' package

### PR DESCRIPTION
**Pull request by kaetemi**

### CODE REVIEW

**Comment by Daegalus** [comment]
Thank you for your changes. I will clean this repo up today and release the new version soon after to pub.

**Comment by mathieujobin** [comment]
this was never released, right?

**Comment by Daegalus** [comment]
Oh shit, I am so sorry, I thought I had. I'll take a look and make sure its dart 2.0 ready and push out an update today.

**Comment by daegalus** [comment]
I have released 1.0, dart 2.0 validated and no crypto library. Sorry again for the oversight

**Comment by mathieujobin** [comment]
thanks

**Pull request merged**
